- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

  - name: Provision a set of instances elk
    ec2:
     key_name: dfed
     group_id: sg-c96112a0
     instance_type: t2.micro
     image: ami-6a2d760f
     wait: true
     region: us-east-2
     exact_count: 1
     count_tag:
       Count: dfed-elk
     instance_tags:
       Name: dfed
       Count: dfed-elk
       func: elk
    register: ec2
