- hosts: localhost
  gather_facts: no
  vars:
   rg_name: dfed
   stg_acct_name: "{{ rg_name }}"
   azure_location: westus
   vm_admin_username: localadmin
 
  tasks:
  # - name: Ensure resource group 
  #   azure_rm_resourcegroup:
  #    name: "{{ rg_name }}"
  #    location: "{{ azure_location }}"
      
  # - name: Ensure storage account 
  #   azure_rm_storageaccount:
  #    name: "{{ stg_acct_name }}"
  #    location: "{{ azure_location }}"
  #    account_type: Premium_LRS
  #    resource_group: "{{ rg_name }}"

  # - name: Ensure virtual network
  #   azure_rm_virtualnetwork: 
  #    name: dfed-vnet01
  #    location: "{{ azure_location }}"
  #    resource_group: "{{ rg_name }}"
  #    address_prefixes_cidr: ["10.4.0.0/16"]

  # - name: Ensure subnet
  #   azure_rm_subnet:
  #    name: dfed-vnet01-subnet001
  #    resource_group: "{{ rg_name }}"
  #    virtual_network_name: dfed-vnet01
  #    address_prefix_cidr: 10.4.1.0/24

  # - name: Create a public IP 
  #   azure_rm_publicipaddress:
  #    resource_group: "{{ rg_name }}"
  #    name: dfedpublicip001

  # - name: Configure network interface 
  #   azure_rm_networkinterface:
  #    name: dfed-elk885
  #    location: "{{ azure_location }}"
  #    resource_group: "{{ rg_name }}"
  #    virtual_network_name: dfed-vnet01
  #    subnet_name: dfed-vnet-subnet001
  #    security_group_name: dfed-elk01
  #    public_ip_address_name: dfedpublicip001

  - name: Ensure virtual machine
    azure_rm_virtualmachine:
     name: 'dfed-elk'
     location: "{{ azure_location }}"
     resource_group: "{{ rg_name }}"
     admin_username: "{{ vm_admin_username }}"
     ssh_password_enabled: False
     ssh_public_keys:
      - path: /home/localadmin/.ssh/authorized_keys
        key_data: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC6wF1e5dW/oborh0eMjhAAwZKbdqpFTduvmM6thgh1h0t76VOLy6dHnVhfl7PsUsIQMplXy6KYOIYQKcDGb3agfnD+GNyNmpYL5Kr1H0f57pbI8c2ZJXKPS2C7VUf2jZ17/S63MXHSvHw/gWEkelDSp641XjS0NxgLTbUl8en1wbX/YC7p1VGEd5UH0Y/N3T98HDkeQnAVXZ2fzjbpvC5C9lJvViPsbBHBe4jZGNjREEgYbuV3uVTWMnZxvGCCCz9s/WRd5WMNY69Z1a5BGxorfxnBH9qrA61hnFzsD+Bil8ewzR/AyIO+jN7eZBP1qi1JzL7X6P+vG6MCz+6nnigNoii9UWP+dXFB4TPVQJlUgnunXiSwrtJ2JcxIjeTSezPJkx/WOqXIV4AnGiuHSgKiYBUnjKc2qrWr0YvHBBSsIvFe00yNR0blzYuWcbiF/krHuk7pqzgmyahKQUBNNejMgMH0E4XDujSrRsCJNMdB134jpVthnR3ZbAE7FYTbQLUhGL6/Y4854iBCvGzLevi1gT7cf4omXMXJ8Di7axetJCiA1GUt6uRHa77NDp6vlxQFgz3RWfOUU1NpNOsqdJy0RXpIyjJG0tqc7Fh6pR69RPPTdUu0UU8cXLm9JnCx2/IMDuCqE80OVLQyYoOMYcanbgZNNj+0NhQdHs4iZuE7Dw== dfed@sterling'
     image: 
       publisher: OpenLogic
       offer: CentOS
       sku: 7.3
       version: latest
     network_interface_names: dfed-elk885
     virtual_network_name: dfed-vnet01
     subnet_name: dfed-vnet-subnet001
     open_ports: [22,80,443]
     storage_account_name: "{{ stg_acct_name }}"
     vm_size: Standard_DS1
   register: vm_output

  - add_host:
     name: "{{ vm_output.ansible_facts.azure_vm.name }}"
     groups: tag_func_elk
     ansible_user: localadmin
     ansible_connection: ssh
     ansible_host: "{{ vm_output.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"

- hosts: tag_func_elk
  gather_facts: no
  
  pre_tasks:
  - name: Ensure ssh is answering
    local_action: wait_for
    args:
     host: "{{ ansible_host | default(inventory_hostname) }}"
     port: 22






